###

GET http://localhost:8090/employees/

###

DELETE http://localhost:8090/employees/4

###

POST http://localhost:8090/employees/
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Developer",
  "phoneNumber": "1234567890"
}

###

PUT http://localhost:8090/employees/4
Content-Type: application/json

    {
    "firstName": "januczke"
    }



