version: '3'
services:
  database:
    ports:
      - "5432:5432"
    expose:
      - 5432
    image: "postgres:15-alpine3.18" # use latest official postgres version
    env_file:
      - Database.env # configure postgres
    volumes:
      - ./data/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "pms_database", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  Liquibase:
    # Image to be pulled from Docker Hub
    image: liquibase/liquibase:4.9.1
    # Name of the container
    container_name: Liquibase_container
    # Setting depends_on to PostgreSQL container to wait till the service is ready to accept connections
    depends_on:
      database:
        condition: service_healthy

    # Volume to add the liquibase collection of scripts
    volumes:
      - ./database/sql/liquibase/changeLog/:/liquibase/changelog/
    # Command to run the liquibase update service
    command: --defaults-file=/liquibase/changelog/liquibase.properties update

volumes:
  database-data: # named volumes can be managed easier using docker-compose 